import json
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

sentences = [
    "Where is the Marina Beach?",
    "What is the chemical formula for water?",
    "Have you finished your homework?",
    "Why is the sky blue?",
    "Who won the cricket match yesterday?",
    "How do you make filter coffee?",
    "Is it going to rain today in Chennai?",
    "When does the next train to Bengaluru leave?",
    "Can you help me with this problem?",
    "Do you understand the instructions?",
    "Which movie should we watch tonight?",
    "Whose book is this on the table?",
    "Are you feeling better now?",
    "How many states are there in India?",
    "What time is it?",
    "Should I call you later?",
    "May I come in?",
    "Did you see the news this morning?",
    "What's for dinner?",
    "Why did you choose this career path?",
    "Who is the current Prime Minister of India?",
    "Where did you go on your last vacation?",
    "How long does it take to get to the airport from here?",
    "Is this the right way to the temple?",
    "What kind of music do you like?",
    "Have you ever visited another country?",
    "Could you tell me your name again?",
    "What are your plans for the weekend?",
    "Does this bus go to T. Nagar?",
    "Who wrote the book 'Ponniyin Selvan'?",
    "Is it hot outside?",
    "The human body has 206 bones.",
    "New Delhi is the capital of India.",
    "The speed of light is approximately 299,792 kilometers per second.",
    "The River Nile is the longest river in the world.",
    "Chennai is the capital of the state of Tamil Nadu.",
    "The chemical symbol for gold is Au.",
    "Mount Everest is the highest mountain on Earth.",
    "The planet Mars is also known as the Red Planet.",
    "Water boils at 100 degrees Celsius at sea level.",
    "The currency of Japan is the Yen.",
    "William Shakespeare wrote 'Hamlet'.",
    "The Great Wall of China is more than 21,000 kilometers long.",
    "The Amazon rainforest is the largest tropical rainforest in the world.",
    "A decade is a period of 10 years.",
    "The national animal of India is the Bengal tiger.",
    "The earth's circumference is about 40,075 kilometers.",
    "The heart is a muscular organ that pumps blood.",
    "Photosynthesis is the process used by plants to convert light into energy.",
    "The Indian Space Research Organisation (ISRO) was founded in 1969.",
    "Spiders have eight legs.",
    "The freezing point of water is 0 degrees Celsius.",
    "The Pacific Ocean is the largest and deepest ocean on Earth.",
    "The atomic number of Carbon is 6.",
    "The Mona Lisa was painted by Leonardo da Vinci.",
    "India gained independence on August 15, 1947.",
    "A leap year occurs every four years.",
    "The sun is a star.",
    "The primary colours are red, yellow, and blue.",
    "There are seven continents in the world.",
    "The chemical formula for table salt is NaCl.",
    "Valluvar Kottam is a monument in Chennai dedicated to the poet Thiruvalluvar.",
    "The moon orbits the Earth.",
    "Penguins are flightless birds.",
    "The metric system is a decimal system of measurement.",
    "Jupiter is the largest planet in our solar system.",
    "The Taj Mahal is located in Agra.",
    "Diamond is the hardest known natural material.",
    "The national flower of India is the lotus.",
    "There are 24 hours in a day.",
    "The Bay of Bengal is to the east of Chennai.",
    "The mango was juicy, sweet, and incredibly ripe.",
    "A gentle breeze rustled the leaves of the banyan tree.",
    "The old temple had intricate carvings on its stone walls.",
    "Her saree was a vibrant shade of peacock blue with a golden border.",
    "The air was thick with the smell of jasmine and rain-soaked earth.",
    "He had a deep, resonant voice that commanded attention.",
    "The auto-rickshaw was painted bright yellow and green.",
    "From the top of the hill, the city looked like a carpet of twinkling lights.",
    "The dosa was thin, crispy, and served with three different chutneys.",
    "The sky was a canvas of orange, pink, and purple hues during sunset at the beach.",
    "The stray dog had soft brown eyes and a perpetually wagging tail.",
    "The library was quiet, with towering shelves filled with old, leather-bound books.",
    "His smile was warm and genuine, instantly putting everyone at ease.",
    "The coffee was strong, dark, and slightly bitter.",
    "The streets of Mylapore are narrow and bustling with activity.",
    "The cat moved with a sleek, silent grace.",
    "Her hair was long, black, and tied in a neat braid.",
    "The building was a modern structure made of glass and steel.",
    "The sound of the waves crashing on the shore was rhythmic and soothing.",
    "The room was sparsely furnished but felt clean and airy.",
    "The child's laughter was infectious and joyful.",
    "The fabric felt smooth and cool to the touch.",
    "It was a hot and humid afternoon, typical for Chennai in August.",
    "The monument was ancient and imposing.",
    "The music was loud and energetic.",
    "The spices in the biryani were fragrant and perfectly balanced.",
    "He wore a simple white veshti and a clean cotton shirt.",
    "The traffic was dense and moved at a crawl.",
    "The flowers in the market were a riot of colors.",
    "His face was weathered, with lines that told a story of a long life.",
    "Mix the flour and water to form a dough.",
    "Turn right at the next traffic light.",
    "Please submit your report by Friday.",
    "Insert your card into the ATM slot.",
    "Boil the milk before drinking it.",
    "Press the green button to start the machine.",
    "Write your name at the top of the paper.",
    "Take one tablet twice a day after meals.",
    "Add two spoons of sugar to the tea.",
    "To save the document, press Control + S.",
    "Unplug all appliances before leaving the house.",
    "First, chop the onions and tomatoes finely.",
    "Read the terms and conditions carefully before signing.",
    "Wear a helmet while riding a two-wheeler.",
    "Speak clearly into the microphone.",
    "Wait for the signal to turn green before crossing the road.",
    "Fill in the form using a black pen.",
    "Assemble the parts according to the diagram.",
    "Do not feed the animals at the zoo.",
    "Keep your belongings safe.",
    "Stir the mixture continuously to avoid lumps.",
    "Please form a queue.",
    "Log in with your username and password.",
    "Lower the flame and let it simmer for ten minutes.",
    "Apply a thin layer of cream to the affected area.",
    "Close all windows before it starts raining.",
    "Switch off the lights and fans when not in use.",
    "Charge your phone before you leave.",
    "Always wash your hands before eating.",
    "Follow the marked trail to reach the summit.",
    
    "The Earth's rotation on its axis causes day and night.",
    "We feel hot due to the high humidity, which prevents sweat from evaporating quickly.",
    "A rainbow is formed when sunlight is scattered from raindrops into the colors of the spectrum.",
    "Cars move because the engine burns fuel, which creates pressure to push pistons.",
    "Inflation is the rate at which the general level of prices for goods and services is rising.",
    "The company's profits fell because of increased competition and rising raw material costs.",
    "The project was delayed due to unforeseen logistical challenges.",
    "He was late because his train was cancelled.",
    "Leaves are green because they contain a pigment called chlorophyll.",
    "The purpose of a vaccine is to stimulate the immune system to produce antibodies.",
    "A solar eclipse occurs when the Moon passes between the Sun and Earth.",
    "Iron rusts as a result of a chemical reaction with oxygen and water.",
    "Earthquakes are caused by the movement of tectonic plates.",
    "Traffic jams happen when the volume of traffic exceeds the road's capacity.",
    "We need to sleep in order for our bodies and minds to rest and repair themselves.",
    "A democracy is a system of government where citizens exercise power by voting.",
    "The internet works by connecting billions of devices worldwide through a network of cables and wireless signals.",
    "The monsoon season brings heavy rainfall to India, which is vital for agriculture.",
    "A fuse blows to protect an electrical circuit from excessive current.",
    "Sound travels in waves through a medium like air or water.",
    "The stock market fluctuates based on supply, demand, and investor sentiment.",
    "Spiders spin webs to catch their prey.",
    "You feel tired after exercise because your muscles have used up their energy stores.",
    "The story is about a king who renounced his throne for a spiritual life.",
    "The reason we add salt to food is to enhance its flavor.",
    "A leap year exists to keep the calendar year synchronized with the astronomical year.",
    "The judiciary's role is to interpret laws and administer justice.",
    "The food chain describes how energy is transferred from one living organism to another.",
    "Metals are good conductors of electricity because their electrons can move freely.",
    "Writing helps clarify your thoughts because it forces you to organize them logically.",
    
    "I think Murugan Idli Shop has the best idlis in Chennai.",
    "That movie was incredibly boring.",
    "In my opinion, public transportation should be free for everyone.",
    "The new policy seems like a step in the right direction.",
    "Blue is the most beautiful color.",
    "I believe that honesty is the most important virtue.",
    "He is probably the best cricketer of his generation.",
    "This sambar is a bit too spicy for my taste.",
    "Reading books is a better hobby than watching television.",
    "The weather today is absolutely perfect.",
    "I feel that modern art is often misunderstood.",
    "That was the worst decision the team could have made.",
    "The service at that restaurant was excellent.",
    "Traveling by train is more enjoyable than traveling by plane.",
    "She is the most talented singer in the industry today.",
    "It seems to me that the problem is more complicated than it looks.",
    "The book's ending was very disappointing.",
    "I would argue that technology has made us less social.",
    "I prefer tea over coffee.",
    "It's better to live in a city than in the countryside.",
    "That song always makes me happy.",
    "He has a wonderful sense of humor.",
    "The government should invest more in renewable energy.",
    "I find history to be a fascinating subject.",
    "This is the most delicious biryani I have ever tasted.",
    "I think we should postpone the meeting.",
    "Learning a new language is a rewarding experience.",
    "It feels like the traffic is getting worse every year.",
    "To be honest, I didn't like the play very much.",
    "The local filter coffee is arguably the best in the world.",
    
    "Be quiet in the library.",
    "Finish your dinner.",
    "Do not touch the exhibits.",
    "Stand up straight.",
    "Clean your room.",
    "Stop making that noise.",
    "Pay attention to the speaker.",
    "Report to the office immediately.",
    "Get out of the way.",
    "Drive carefully.",
    "Don't be late for the meeting.",
    "Hand me that file.",
    "Turn off your mobile phones.",
    "Wait here until I return.",
    "Follow me.",
    "Tell me the truth.",
    "Do not argue.",
    "Mind the gap.",
    "Wear your seatbelt.",
    "Send the email now.",
   
    "What a fantastic performance!",
    "I can't believe we won!",
    "That's absolutely brilliant!",
    "Ouch, that hurts!",
    "Wow, look at that view!",
    "Happy birthday!",
    "Oh no, I forgot my keys!",
    "Thank goodness you're safe!",
    "It's so hot today!",
    "What a mess!",
    "Help!",
    "Congratulations on your success!",
    "How wonderful!",
    "I'm so excited for the trip!",
    "That's a huge spider!",
    "What a pity!",
    "Finally, it's the weekend!",
    "That was a close call!",
    "I did it!",
    "This is the best day ever!",
    
    "I think the Chennai Super Kings will win the match tonight.",
    "It will probably rain this evening.",
    "The stock market is likely to fall next week.",
    "She will surely get the promotion.",
    "The traffic is going to be terrible during the festival.",
    "I predict that technology will make many current jobs obsolete in 20 years.",
    "This new restaurant won't last more than a year.",
    "He is going to be late, as usual.",
    "The price of gold will likely increase.",
    "I bet you'll love this movie.",
    "We might see a breakthrough in AI research soon.",
    "The company is expected to announce its quarterly results tomorrow.",
    "The flight will probably be delayed due to the bad weather.",
    "She will be a great leader one day.",
    "This problem will not be easy to solve.",
    "The next generation of smartphones will have even better cameras.",
    "I expect to finish the project by the deadline.",
    "The summers are projected to get hotter each year.",
    "There's a good chance we'll meet them at the party.",
    "The metro expansion project will likely be completed by 2026.",
    
    "If you add more spice, the dish will taste better.",
    "If the plant is given more sunlight, it will grow faster.",
    "If we leave early, we might avoid the traffic.",
    "If the experiment is successful, it could revolutionize the industry.",
    "If a user clicks this button, then they should be taken to the homepage.",
    "Perhaps if we change the marketing strategy, sales will improve.",
    "If the temperature drops below freezing, then the water will turn to ice.",
    "If demand for the product increases, then its price will also increase.",
    "If the soil has more nutrients, then the crops will yield a better harvest.",
    "If you practice daily, your skills will improve significantly.",
    # Requests
    "Could you please pass me the salt?",
    "Would you mind opening the window?",
    "Can you lend me a pen, please?",
    "Could you please speak a little louder?",
    "I would appreciate it if you could send me the details.",
    "Can you hold this for a moment?",
    "Would it be possible to get me a glass of water?",
    "Please, could you show me the way to the post office?",
    "May I have your attention, please?",
    "Could you check this calculation for me?",
    "Would you be able to help me move this table?",
    "Can I borrow your charger?",
    "Please let me know your decision by tomorrow.",
    "Could you drop me at the station?",
    "May I ask you a personal question?",
    "Would you be so kind as to give me a discount?",
    "Can you please repeat that?",
    "I was wondering if you could recommend a good book.",
    "Would you please take a picture of us?",
    "Kindly grant me leave for two days.",
    
    "Hello, how are you today?",
    "Good morning!",
    "Hi there!",
    "Welcome to our home.",
    "It's a pleasure to meet you.",
    
    "Goodbye, see you later.",
    "Take care.",
    "Have a great day!",
    "Farewell and good luck.",
    "See you tomorrow.",
    
    "Actions speak louder than words.",
    "The early bird catches the worm.",
    "A picture is worth a thousand words.",
    "Don't count your chickens before they hatch.",
    "Honesty is the best policy.",
    "Practice makes perfect.",
    "Where there's a will, there's a way.",
    "Two wrongs don't make a right.",
    "When in Rome, do as the Romans do.",
    "All that glitters is not gold.",
    
    "I am going to the market this evening.",
    "She is reading a book in the garden.",
    "The meeting is scheduled for 3 PM.",
    "I have finished my work for the day.",
    "They are playing cricket in the park.",
    "My flight was delayed by an hour.",
    "I need to buy some vegetables.",
    "The cat is sleeping on the sofa.",
    "He works as a software engineer.",
    "We live in Chennai.",
    "I sent you an email yesterday.",
    "The phone is ringing.",
    "My favourite colour is green.",
    "I am learning to play the guitar.",
    "The children are watching television.",
    "I have a doctor's appointment tomorrow.",
    "The power went out an hour ago.",
    "She prefers to travel by bus.",
    "My head hurts.",
    "The restaurant is closed on Mondays."
]
labels = [
    # Questions
    "Question", "Question", "Question", "Question", "Question", "Question", "Question", "Question", "Question", "Question",
    "Question", "Question", "Question", "Question", "Question", "Question", "Question", "Question", "Question", "Question",
    "Question", "Question", "Question", "Question", "Question", "Question", "Question", "Question", "Question", "Question",
    "Question",
    # Facts
    "Fact", "Fact", "Fact", "Fact", "Fact", "Fact", "Fact", "Fact", "Fact", "Fact",
    "Fact", "Fact", "Fact", "Fact", "Fact", "Fact", "Fact", "Fact", "Fact", "Fact",
    "Fact", "Fact", "Fact", "Fact", "Fact", "Fact", "Fact", "Fact", "Fact", "Fact",
    "Fact", "Fact", "Fact", "Fact", "Fact", "Fact", "Fact", "Fact", "Fact", "Fact",
    # Descriptions
    "Description", "Description", "Description", "Description", "Description", "Description", "Description", "Description", "Description", "Description",
    "Description", "Description", "Description", "Description", "Description", "Description", "Description", "Description", "Description", "Description",
    "Description", "Description", "Description", "Description", "Description", "Description", "Description", "Description", "Description", "Description",
    # Instructions
    "Instruction", "Instruction", "Instruction", "Instruction", "Instruction", "Instruction", "Instruction", "Instruction", "Instruction", "Instruction",
    "Instruction", "Instruction", "Instruction", "Instruction", "Instruction", "Instruction", "Instruction", "Instruction", "Instruction", "Instruction",
    "Instruction", "Instruction", "Instruction", "Instruction", "Instruction", "Instruction", "Instruction", "Instruction", "Instruction", "Instruction",
    # Explanations
    "Explanation", "Explanation", "Explanation", "Explanation", "Explanation", "Explanation", "Explanation", "Explanation", "Explanation", "Explanation",
    "Explanation", "Explanation", "Explanation", "Explanation", "Explanation", "Explanation", "Explanation", "Explanation", "Explanation", "Explanation",
    "Explanation", "Explanation", "Explanation", "Explanation", "Explanation", "Explanation", "Explanation", "Explanation", "Explanation", "Explanation",
    # Opinions
    "Opinion", "Opinion", "Opinion", "Opinion", "Opinion", "Opinion", "Opinion", "Opinion", "Opinion", "Opinion",
    "Opinion", "Opinion", "Opinion", "Opinion", "Opinion", "Opinion", "Opinion", "Opinion", "Opinion", "Opinion",
    "Opinion", "Opinion", "Opinion", "Opinion", "Opinion", "Opinion", "Opinion", "Opinion", "Opinion", "Opinion",
    # Commands
    "Command", "Command", "Command", "Command", "Command", "Command", "Command", "Command", "Command", "Command",
    "Command", "Command", "Command", "Command", "Command", "Command", "Command", "Command", "Command", "Command",
    # Exclamations
    "Exclamation", "Exclamation", "Exclamation", "Exclamation", "Exclamation", "Exclamation", "Exclamation", "Exclamation", "Exclamation", "Exclamation",
    "Exclamation", "Exclamation", "Exclamation", "Exclamation", "Exclamation", "Exclamation", "Exclamation", "Exclamation", "Exclamation", "Exclamation",
    # Predictions
    "Prediction", "Prediction", "Prediction", "Prediction", "Prediction", "Prediction", "Prediction", "Prediction", "Prediction", "Prediction",
    "Prediction", "Prediction", "Prediction", "Prediction", "Prediction", "Prediction", "Prediction", "Prediction", "Prediction", "Prediction",
    # Hypotheses
    "Hypothesis", "Hypothesis", "Hypothesis", "Hypothesis", "Hypothesis", "Hypothesis", "Hypothesis", "Hypothesis", "Hypothesis", "Hypothesis",
    # Requests
    "Request", "Request", "Request", "Request", "Request", "Request", "Request", "Request", "Request", "Request",
    "Request", "Request", "Request", "Request", "Request", "Request", "Request", "Request", "Request", "Request",
    # Greetings
    "Greeting", "Greeting", "Greeting", "Greeting", "Greeting",
    # Farewells
    "Farewell", "Farewell", "Farewell", "Farewell", "Farewell",
    # Proverbs
    "Proverb", "Proverb", "Proverb", "Proverb", "Proverb", "Proverb", "Proverb", "Proverb", "Proverb", "Proverb",
    # Statements
    "Statement", "Statement", "Statement", "Statement", "Statement", "Statement", "Statement", "Statement", "Statement", "Statement",
    "Statement", "Statement", "Statement", "Statement", "Statement", "Statement", "Statement", "Statement", "Statement", "Statement"
]


vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(sentences)
clf = LogisticRegression()
clf.fit(X_train,labels)

def load_snippets(json_path):
    with open(json_path, "r", encoding="utf-8") as f:
        return json.load(f)

def filter_bad_snippets(snippets):
    return [s for s in snippets if len(s.strip()) > 30]

def categorize_snippets_ml(all_snippets):
    categorized = {'Question': [], 'Description': [], 'Conclusion': [], 'Other': []}
    for url, snippets in all_snippets.items():
        filtered = filter_bad_snippets(snippets)
        X_test = vectorizer.transform(filtered)
        preds = clf.predict(X_test)
        for snippet, label in zip(filtered, preds):
            categorized[label if label in categorized else 'Other'].append({'url': url, 'text': snippet})
    return categorized

def main():
    all_snippets = load_snippets("snippets.json")
    categorized = categorize_snippets_ml(all_snippets)
    with open("categorized_snippets.json", "w", encoding="utf-8") as f:
        json.dump(categorized, f, ensure_ascii=False, indent=2)

if __name__ == "__main__":

    main()
